markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: Yilong Hu
    quote: Stay hungry, stay foolish.
    description: My Personal Blogs
    title: TechHub
    url: http://huyilong.github.io/ 
    disqus: huyilong
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: Yilong Hu
    email: hu.yilong@wustl.edu  
    github: huyilong 
    linkedin: www.linkedin.com/in/huyilong
    facebook: hu.yilong.aaron
    gplus: 103958170808553329434/about
    logo: http://huyilong.github.io/res/img/logo.png

